on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - "3.11.1"
          - "3.10.9"
          - "3.9.16"
          - "3.8.15"
        include:
          - os: windows-2022
            python-version: "3.8.10"
          - os: windows-2022
            python-version: "3.9.13"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Set Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: "pip install -r dev-requirements.txt"

      - name: Run linter
        run: flake8 src
        continue-on-error: true

      - name: Run tests
        run: pytest -n 3
